[#104] 기능: 별점 슬라이드 기능 구현
depromeet/bread-map-front pull request #110
Opened 2021-11-15 14:39 UTC by jellybrown

## 개요 및 변경 사항 
- 별점 슬라이드 기능 구현
- `react-use` 라이브러리의 `useSlider`를 참고했습니다.  
 기능 👉  https://github.com/streamich/react-use/blob/master/src/useSlider.ts
 UI 👉 https://github.com/streamich/react-use/blob/master/docs/useSlider.md

## 관련 이슈 

closes #104 

## 추가 구현 필요사항
- 필요시 `StarScore` 컴포넌트 내부에 있는 상태값 분리
- 필요시 추후 코드량 줄이기

## 스크린샷 
<img src="https://user-images.githubusercontent.com/59910838/141800202-d708f70e-774b-4356-9290-a156eaf7efa5.png" width="150"/>

2021-11-16 06:25 UTC, wooogi123 requested changes

2021-11-16 06:25 UTC, wooogi123 commented on web/src/components/common/StarScore/index.tsx
> +  };
요 부분 value의 값이 0 ~ 1의 boundary라서 요렇게 하신건가요? 그렇다면 그냥 * 5로 score 세팅해도 될 것 같아서요!

2021-11-16 06:25 UTC, wooogi123 commented on web/src/utils/slideUtils.ts
> +export const isNavigator = typeof navigator !== 'undefined';
해당 부분은 따로 뽑을 필요 없이 slider 안에 넣어도 되지 않을까 싶어요! 현재 시점에서는 한 곳에서 밖에 사용하지 않을 유틸 함수라서 따로 뽑아내는 큰 의미는 없을 것 같습니다.

2021-11-16 06:25 UTC, wooogi123 commented on web/src/components/common/StarScore/useSlider.ts
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
이거랑 137 line의 lint-disabled는 왜 하신건가요?? 꼭 필요한 부분인가 싶어서요!

2021-11-16 08:16 UTC, HanCheo commented on web/src/components/common/StarScore/index.tsx
> +  };
`const percent = Math.round(value * 5)` 이렇게 해주면 0,1,2,3,4,5 중 하나에영

2021-11-17 13:17 UTC, jellybrown commented on web/src/components/common/StarScore/index.tsx
> +  };
넵넵 수정하겠습니다~!

2021-11-17 13:48 UTC, jellybrown commented on web/src/components/common/StarScore/useSlider.ts
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
<img src="https://user-images.githubusercontent.com/59910838/142210328-faf917ba-57db-4ff8-8cd0-b1c29aa9f8fb.png"  width="400"/>
이런 에러문구가 나와서요! ㅠ.ㅠ

2021-11-17 14:00 UTC, seokzin approved these changes
고생하셨습니다
useSlider 되게 유용한 라이브러리네요!
특히 분기점으로 커서를 맞춰 주는 게 맘에 드네요

2021-11-25 07:06 UTC, HanCheo approved these changes

2021-11-25 07:07 UTC, merged