[#100] 기능: 빵집 상세페이지 full screen 용 추가
depromeet/bread-map-front pull request #111
Opened 2021-11-17 08:09 UTC by HanCheo

## 개요 및 변경 사항 

페이지 추가 및 데이터 읽는 형태만 되었습니다.
디자인 부분 많이 깔끔하지 못한부분이 조금 보이실 수 있는데 ..,ㅠ
남은 페이지 진행이 우선인것 같아 우선순위좀 내릴께요..

1. .env file에`NEXT_PUBLIC_BASE_URI=http://localhost:3000` 넣어주셔야 Mock서버 정상 동작되용 모르시는분 참고

## 관련 이슈 

closes #100

## 추가 구현 필요사항

## 스크린샷 
![Nov-17-2021 17-04-18](https://user-images.githubusercontent.com/38929712/142159948-a564834d-c03f-408f-a862-64061aa78470.gif)

2021-11-17 08:24 UTC, wooogi123 requested changes

2021-11-17 08:24 UTC, wooogi123 commented on web/src/components/breadStore/StoreDetailTabs.tsx
> +  const _currentTab = isTab(tab) ? tab : 'home';
요거 private 의미로 `_currentTab` 으로 쓰신건가요? `currentTab`도 차이 없을 것 같아서요

2021-11-17 08:24 UTC, wooogi123 commented on web/src/components/breadStore/StoreDetailTabs.tsx
> +          {_currentTab === 'info' && <InfoSection bakeryData={data} />}
이 부분에서 결국 prop으로 넘어가는 부분이 bakeryData니까, bakeryId만 넘겨주고 각 컴포넌트에서 데이터를 사용하는 구조가 더 깔금할 것 같아요!

2021-11-17 08:24 UTC, wooogi123 commented on web/src/components/breadStore/TabContents/HomeSection/MenuCardList.tsx
> +              <img src={menu.imgPath} alt={'menu'} />
이거 모킹된 데이터로 사용해주신거 같은데 imgPath가 없을 경우 placeholder image로 보여지는 부분 처리도 같이 진행하면 좋을 것 같습니다

2021-11-17 08:24 UTC, wooogi123 commented on web/src/components/breadStore/TabContents/HomeSection/ReviewCardList.tsx
> +                ))}
이 부분도 위랑 같이 모킹 데이터로 처리하면 좋을 것 같아요!

2021-11-17 11:58 UTC, HanCheo commented on web/src/components/breadStore/TabContents/HomeSection/ReviewCardList.tsx
> +                ))}
확인해씁니당 :)
리뷰부분은 있으면 보여주고 없으면 안보여주는 형태여서 안해두 되지 않을까용..?

2021-11-17 11:59 UTC, HanCheo commented on web/src/components/breadStore/StoreDetailTabs.tsx
> +  const _currentTab = isTab(tab) ? tab : 'home';
아 맞아요 원래 tab을 props로 받고있었는데 변경하고 수정을 안했네요.ㅠ

2021-11-17 12:20 UTC, HanCheo commented on web/src/components/breadStore/StoreDetailTabs.tsx
> +          {_currentTab === 'info' && <InfoSection bakeryData={data} />}
요거 궁금한게 있는데용
useSWR 부모에서 부르고 동일한 쿼리 자식에서 또불러도 괜찮나요??
bakeryHeader에서 쓰는 bakeryName때문에 그러는뎅...

2021-11-17 12:27 UTC, wooogi123 commented on web/src/components/breadStore/StoreDetailTabs.tsx
> +          {_currentTab === 'info' && <InfoSection bakeryData={data} />}
https://swr.vercel.app/docs/revalidation#disable-automatic-revalidations

위 구조처럼 이미 stale된 데이터를 가져오는 구조로 사용하면 문제 없을 것 같아요!

2021-11-17 12:28 UTC, wooogi123 commented on web/src/components/breadStore/TabContents/HomeSection/ReviewCardList.tsx
> +                ))}
아하 넵 이미지가 없는 경우에는 text만 보여주는 구조니까 안해도 될 것 같아요!

2021-11-17 14:15 UTC, seokzin approved these changes
코드 보면서 항상 배워갑니다..

2021-11-20 07:37 UTC, wooogi123 requested changes

2021-11-20 07:37 UTC, wooogi123 commented on web/src/components/breadStore/StoreDetailTabs.tsx
> +  if (Array.isArray(tabName) || !tabName || !tabs.includes(tabName)) {
이거 각각의 조건들을 떼어내서 더 명시적으로 변경해도 좋을 것 같아요. 그리고 undefined check의 경우는 `tabName === undefined`로 보다 명시적으로 변경하는게 좋을 것 같습니다!

2021-11-20 07:37 UTC, wooogi123 commented on web/src/components/breadStore/StoreDetailTabs.tsx
> +  const _bakeryId = id ? +id : 0;
요거 그냥 `bakeryId`로 지정해도 좋을 것 같아요

2021-11-20 09:24 UTC, HanCheo commented on web/src/components/breadStore/StoreDetailTabs.tsx
> +  if (Array.isArray(tabName) || !tabName || !tabs.includes(tabName)) {
넵 :)

2021-11-22 09:15 UTC, wooogi123 approved these changes

2021-11-22 09:15 UTC, merged