[기능/#105] 프로필 가보고 싶어요 탭 구현
depromeet/bread-map-front pull request #130
Opened 2021-12-04 04:37 UTC by seokzin

## 개요 및 변경 사항 

## 관련 이슈 

closes 

## 추가 구현 필요사항

## 스크린샷

2021-12-04 05:40 UTC, wooogi123 requested changes
저희 패키지 매니저를 yarn berry를 통해 컨트롤 하고 있어서 package-lock 파일은 없어도 될 것 같습니다!

2021-12-04 07:02 UTC, wooogi123 approved these changes

2021-12-04 11:27 UTC, HanCheo approved these changes
똬봉

2021-12-04 11:34 UTC, HanCheo commented
가보고 싶어요, 가봤어요가 필터 말고는 거의 동일 로직 같은데 한 번에 PR 해도 괜찮을지? 
- 넵 좋아용 :) 
- 요런거는 profile 내에서 중복이니까 profile 폴더네에서 중복 처리 한꺼번에하면 좋아보여용
- 예시는 components/addBakery/AddBakeryInput 폴더 같은 형태루 뽑아쓰심 될것같아용
- components/addBakery/AddBakeryInfo에서 사용하는 형태 참고하심됩니당

가보고 싶어요, 가봤어요 데이터를 구분 짓는 flag 표현을 어떻게 할 지 고민 
- 가보고싶어요 : 깃발을 꼽은형태
- 가봤어요 : 리뷰를 작성한 형태??
- 리뷰..???: 리뷰를 작성한..??
 중복이 있는 것같네요.. 디자이너분들께 한번 여쭤보는게 맞을 것 같습니다 !

2021-12-05 07:25 UTC, jellybrown approved these changes
고생하셨습니다 ~~!

2021-12-06 03:53 UTC, merged