[#149] 기능: addBread api 연결
depromeet/bread-map-front pull request #152
Opened 2021-12-11 05:00 UTC by jellybrown

## 개요 및 변경 사항 
- 빵등록 api 연결

## 관련 이슈 

closes 
close #149 

## 추가 구현 필요사항
- 사진 미리보기
- s3 api 연결

2021-12-11 05:09 UTC, wooogi123 requested changes

2021-12-11 05:09 UTC, wooogi123 commented on web/src/remotes/hooks/useCreateBakeryMenuReview.ts
> +const postCreateBakeryMenuReview = async ({
@jellybrown 요거 파일 명이랑 같이 맞추면 좋을 것 같아요

2021-12-11 05:10 UTC, HanCheo commented on web/src/remotes/hooks/useCreateBakeryMenuReview.ts
> +const postCreateBakeryMenuReview = async ({
요거 맞추시고 나서 제가 이어서 하겠스빈당

2021-12-11 05:10 UTC, HanCheo approved these changes
고생하셧습니당

2021-12-11 05:15 UTC, seokzin approved these changes

2021-12-12 23:44 UTC, jellybrown commented on web/src/remotes/hooks/useCreateBakeryMenuReview.ts
> +const postCreateBakeryMenuReview = async ({
저파일 안쓰고있긴 한데...(파일명때문에 오류나서 그냥 MainAdd.tsx에 추가했어요😭) 
일단 수정해보도록 하겠습니다~!

2021-12-13 06:29 UTC, merged