[#169] 기능 : url 드롭다운 기능 구현
depromeet/bread-map-front pull request #175
Opened 2021-12-18 06:05 UTC by jellybrown

## 개요 및 변경 사항 
- url 드롭다운 기능 구현

## 관련 이슈 

closes #169 

## 스크린샷 

<img src="https://user-images.githubusercontent.com/59910838/146631208-421396ec-bdc6-4a22-af92-960f9cfbfe80.png" width="200"/>
<img src="https://user-images.githubusercontent.com/59910838/146631217-7870e943-66bc-4d56-921f-ef9e977cd69c.png" width="200"/>

2021-12-18 06:13 UTC, wooogi123 requested changes

2021-12-18 06:13 UTC, wooogi123 commented on web/src/components/bakery/TabContents/InfoSection/WebSiteList.tsx
> +          ))}
요거 0 index에 있는건 루프 밖으로 뽑아놓고 1 ~ end까지만 `Wrapper > UrlLink`로 묶으면 icon 분기 필요 없이 깔금해 질 것 같아요!

2021-12-18 06:13 UTC, wooogi123 commented on web/src/components/bakery/TabContents/InfoSection/WebSiteList.tsx
> +  padding-left: ${({ paddingLeft }) => `${paddingLeft}px`};
요거 paddingLeft를 prop으로 따로 주입받아서 처리하는 이유가 있나요? prop으로 넘어오는 값도 상수인 것 같아서요!

2021-12-18 06:13 UTC, wooogi123 commented on web/src/components/bakery/TabContents/InfoSection/WebSiteList.tsx
> +  height: ${({ height }) => `${height}px`};
`min-height: 16px` 로 최소 높이를 지정해놓고 open 여부에 따라서 div가 늘어나는 구조로도 가능할 것 같아요!

2021-12-18 06:13 UTC, wooogi123 commented on web/src/components/bakery/TabContents/InfoSection/WebSiteList.tsx
> +  }, [opened]);
밑에 height를 `min-height`로 묶으면 해당 effect는 없어도 될 것 같습니다!

2021-12-18 08:24 UTC, jellybrown commented on web/src/components/bakery/TabContents/InfoSection/WebSiteList.tsx
> +  height: ${({ height }) => `${height}px`};
1

2021-12-18 08:24 UTC, jellybrown commented on web/src/components/bakery/TabContents/InfoSection/WebSiteList.tsx
> +  height: ${({ height }) => `${height}px`};
👍 반영하도록 하겠습니다~!

2021-12-19 14:06 UTC, jellybrown commented on web/src/components/bakery/TabContents/InfoSection/WebSiteList.tsx
> +  padding-left: ${({ paddingLeft }) => `${paddingLeft}px`};
나중에 다른 곳에서 쓰인다면 padding 줄때 또한번 div같은걸로 감싸야 할거같아서 추가했는데 필요없어보인다면 빼겠습니다 :)

2021-12-26 07:45 UTC, HanCheo approved these changes

2021-12-26 09:19 UTC, HanCheo approved these changes

2021-12-26 09:29 UTC, seokzin approved these changes

2021-12-28 13:57 UTC, wooogi123 requested changes

2021-12-28 13:57 UTC, wooogi123 commented on web/src/components/bakery/TabContents/InfoSection/WebSiteList.tsx
> +  }, [urlList]);
요 부분 useMemo를 사용해서 matchedLink를 만들면 어떨까요? dependency가 변경되면 다시 계산하는건 똑같으니까요!

2021-12-29 13:54 UTC, merged