[#15] 디자인: modern.css 추가
depromeet/bread-map-front pull request #18
Opened 2021-09-25 08:14 UTC by HanCheo

## 개요 및 변경 사항 

modern CSS 추가 :)

## 관련 이슈 

Issue #15 

## 추가 구현 필요사항

## 스크린샷

2021-09-25 08:19 UTC, jellybrown reviewed
👍 고생하셨습니다!

2021-09-25 08:22 UTC, seokzin approved these changes
심플하게 CSS 초기화 해줘서 좋네요ㅎㅎ 애용해야겠다

2021-09-25 09:30 UTC, wooogi123 requested changes

2021-09-26 06:18 UTC, HanCheo commented on web/src/styles/globals.ts
> +
옙 !

2021-09-26 08:26 UTC, wooogi123 approved these changes
👍

2021-09-26 10:33 UTC, merged