[#1] 설정 : 이슈, PR 템플릿, 자동 Assignees 추가
depromeet/bread-map-front pull request #2
Opened 2021-09-12 06:35 UTC by HanCheo

## 개요 및 변경 사항 

제곧내 +

기존에 사용하던 부분에서 엄청 조금 수정했습니다.

기존 이슈 템플릿에는 예상완료 시간, 실제 완료시간이 있었는데 
제대로 작성되고 회고 된 적이 많이 없어서 뺏습니다.

## 관련 이슈 

closes #1 

## 추가 구현 필요사항

필요하신 내용이 있다면 추가하거나 수정하셔도 좋습니다 ! :)

## 스크린샷

2021-09-12 07:31 UTC, wooogi123 requested changes
issue template에 relative issue 스텝도 추가되면 좋을꺼같아요!

예를 들어서 issue A 진행중에 task를 더 쪼개서 추가 issue로 만드어서 진행하면, 상위 issue를 같이 링크해두는 방식은 어떨까요?

2021-09-12 07:55 UTC, HanCheo commented
> issue template에 relative issue 스텝도 추가되면 좋을꺼같아요!
> 
> 예를 들어서 issue A 진행중에 task를 더 쪼개서 추가 issue로 만드어서 진행하면, 상위 issue를 같이 링크해두는 방식은 어떨까요?

너무 좋아요 :)
## 관련 이슈
로 추가할께요 !

2021-09-12 07:57 UTC, wooogi123 approved these changes
lgtm 👍

2021-09-13 00:01 UTC, seokzin approved these changes
템플릿 굉장히 유용해요 👍👍

2021-09-13 00:26 UTC, HanCheo commented
간단한거라 바루 머지할께용 :)

2021-09-13 00:26 UTC, merged