[#15] 설정: themeProvicer 설정 추가, prettier 수정
depromeet/bread-map-front pull request #22
Opened 2021-09-26 11:03 UTC by HanCheo

## 개요 및 변경 사항 <!— 해당 Pull Request에 대한 간단한 설명 작성 —>

1. prettier 경로 오류 내용 수정했습니다.
2. themeProvider 설정 추가했습니다.
 - 로컬스토리지 이용해서 현재 테마가 저장 되는 것까지 했는데 그냥 기능만 넣어둔거구요 :)
 - 색상 또는 값을 추가하시려면 `styles/styled.d.ts`에서 타입을 추가하신후 `theme.ts`파일에서 해당 타입명에 색상값을 넣어주시고 사용하시면 됩니다.
- 예시용 파일도 같이 몇개 수정하였습니다. :)
- 필요하시거나 수정하실 내용있으시면 편하게 수정하셔도 됩니다. 

## 관련 이슈 <!— 해당 Pull Request에 대한 자세한 내용을 확인할 수 있는 이슈를 번호로 작성 —>

closes #15 <!— Ex. closes #1 —>
closes #19

## 추가 구현 필요사항

## 스크린샷 <!— 빠른 참고 용 —>

![테마](https://user-images.githubusercontent.com/38929712/134804459-90631c20-b872-458a-9f41-00e347a7bfb1.gif)

2021-09-26 11:26 UTC, wooogi123 commented on web/src/pages/_app.tsx
>      <>
여기랑 line 15 부분 Fragment는 제거해도 될것같습니다

2021-09-26 12:00 UTC, HanCheo commented on web/src/pages/_app.tsx
>      <>
바로반영하겠습니다 👍

2021-09-26 12:00 UTC, wooogi123 commented
_app.tsx의 ThemeProvider, useGlobalTheme 부분을 묶어서 요런식으로 추상화시키는건 어떨까요?

```tsx
styles/BreadmapTheming.tsx

import * as React from 'react';
import { Global, ThemeProvider as EmotionThemeProvider } from '@emotion/react';
import globalStyles from './globals';
import { LightMode, DarkMode } from './theme';
import type { Theme } from '@emotion/react';

type ThemeName = 'dark' | 'light';

const THEME: Record<ThemeName, Theme> = {
  dark: DarkMode,
  light: LightMode,
};

const ThemeNameContext = React.createContext<ThemeName | null>(null);

type ThemeNameDispatch = (themeName: ThemeName) => void;
const ThemeNameDispatchContext = React.createContext<ThemeNameDispatch | null>(null);

interface BreadmapThemeProviderProps {
  children: React.ReactNode;
}

export const BreadmapThemeProvider = ({ children }: BreadmapThemeProviderProps) => {
  const [themeName, setThemeName] = React.useState<ThemeName>('light');

  const handleChangeThemeName = React.useCallback(
    (name: ThemeName) => {
      setThemeName(name);
    },
    [],
  );

  return (
    <EmotionThemeProvider theme={THEME[themeName]}>
      <Global styles={globalStyles} />
      <ThemeNameContext.Provider value={themeName}>
        <ThemeNameDispatchContext.Provider value={handleChangeThemeName}>
          {children}
        </ThemeNameDispatchContext.Provider>
      </ThemeNameContext.Provider>
    </EmotionThemeProvider>
  );
};

export const useThemeName = () => {
  const context = React.useContext(ThemeNameContext);
  if (context === null) throw new Error();
  return context;
};

export const useThemeNameDispatch = () => {
  const dispatch = React.useContext(ThemeNameDispatchContext);
  if (dispatch === null) throw new Error();

  return (payload: ThemeName) => {
    dispatch(payload);
  };
};

```

```ts
pages/_app.tsx

import * as React from 'react';
import { Global } from '@emotion/react';
import {
  BreadmapThemeProvider,
  useThemeName,
  useThemeNameDispatch,
} from '@/styles/BreadmapTheming';
import type { AppProps } from 'next/app';

const Theme: React.FC = ({ children }) => (
  <BreadmapThemeProvider>
    {children}
  </BreadmapThemeProvider>
);

function MyApp({ Component, pageProps }: AppProps) {
  const themeName = useThemeName();
  const themeNameDispatch = useThemeNameDispatch();

  const toggleTheme = () => {
    themeNameDispatch(themeName === 'dark'
      ? 'light'
      : 'dark'
    );
  };

  return (
      <Theme>
        <button onClick={toggleTheme}>테마변경</button>
        <Component {...pageProps} />
      </Theme>
  );
}
```

2021-09-26 12:25 UTC, HanCheo commented
와.. 한수 배워갑니다....
너무 좋네용 적용해볼께요  !

2021-09-27 09:58 UTC, HanCheo commented on web/src/pages/index.tsx
> +
요부분 `_app.tsx` 에서 하면 `BreadmapThemeProvider`이 안만들어진 상태여서 null값 참조 에러로 나오더라구요.

2021-09-27 09:58 UTC, HanCheo commented on web/src/styles/BreadMapTheming.tsx
> +};
요거는 light, dark를 상수화 했습니당

2021-09-27 09:58 UTC, HanCheo commented on web/src/styles/BreadMapTheming.tsx
> +import { createContext, useContext, useState, useCallback } from 'react';
@wooogi123 

저 여기서 궁금해가지구 질문하나 남깁니다.

밑에 단순히 `React.`가 반복되서 예시코드에서 빼긴 했는데..
`useState`로 안쓰시구 `React.useState`로 쓰시는데 혹시 이렇게 사용하시는 장점이나 이유가 있으신가요??
맨날 필요한것만 임포트 해서 쓰다보니까 리액트 이렇게 쓰는건 잘 생각을 못해 봤어서 

리액트용 훅이랑 커스텀훅이랑 구분하기 위해서인가요..?

2021-09-27 09:59 UTC, HanCheo commented on web/src/pages/index.tsx
> +
요부분 `_app.tsx` 에서 하면 `BreadmapThemeProvider`이 안만들어진 상태여서 null값 참조 에러로 나오더라구요.

2021-09-27 10:00 UTC, HanCheo commented on web/src/pages/index.tsx
> +
요부분 `_app.tsx` 에서 하면 `BreadmapThemeProvider`이 안만들어진 상태여서 null값 참조 에러로 나오더라구요.

2021-09-27 10:25 UTC, wooogi123 requested changes

2021-09-27 10:25 UTC, wooogi123 commented on web/src/pages/_app.tsx
> +import * as React from 'react';
요 부분 import는 사용 안하는 부분이라 제거해도 될것같아요!

2021-09-27 10:25 UTC, wooogi123 commented on web/src/pages/index.tsx
> +
이거
```tsx
const Theme: React.FC = ({ children }) => (
  <BreadmapThemeProvider>
    {children}
  </BreadmapThemeProvider>
);

function MyApp({ Component, pageProps }: AppProps) {
  const themeName = useThemeName();
  const themeNameDispatch = useThemeNameDispatch();

  const toggleTheme = () => {
    themeNameDispatch(themeName === 'dark'
      ? 'light'
      : 'dark'
    );
  };

  return (
      <Theme>
        <button onClick={toggleTheme}>테마변경</button>
        <Component {...pageProps} />
      </Theme>
  );
}
```

이런식으로 Theme로 외부에서 묶어도 null error 발생하나요?

2021-09-27 10:25 UTC, wooogi123 commented on web/src/styles/BreadMapTheming.tsx
> +import { createContext, useContext, useState, useCallback } from 'react';
typescript에서 기본적으로 React는 namespace export 되어있어서 저는 주로 React namespace를 import해서 호출하는 형태를 사용합니다! import 구문이 많아지는 문제도 해결할 수 있구요

2021-09-27 10:25 UTC, wooogi123 commented on web/src/styles/BreadMapTheming.tsx
> +};
요거 THEME_NAME 상수가 필요한가요? 컴파일 타임에서 ThemeName type을 통해 걸러질 항목이라 상수 선언 없이 Type: Theme 형태로 사용하면 될것같아서요

2021-09-27 10:25 UTC, wooogi123 commented on web/src/pages/index.tsx
> +  };
이 부분에서 themeName의 경우 `ThemeName`타입으로 추론되고, themeNameDispatch의 경우 `(name: ThemeName) => void`로 추론될꺼라서 THEME_NAME 상수 호출이 필요 없을 것 같습니다

2021-09-27 10:40 UTC, HanCheo commented on web/src/pages/_app.tsx
> +import * as React from 'react';
넵 :)

2021-09-27 10:42 UTC, HanCheo commented on web/src/pages/index.tsx
> +
넵 에초애 `ThemeNameDispatchContext` 이 컨텍스트가 초기화 되는 부분이 `BreadmapThemeProvider `의 내부에 있다보니

내부에서 초기화 되기전에 `useThemeNameDispatch();` 를 불러서 null 참조오류가 나타나더라구용

2021-09-27 10:45 UTC, wooogi123 commented on web/src/pages/index.tsx
> +
아 provider 하위로 context가 주입되니까 그렇네요 👍👍

2021-09-27 10:48 UTC, HanCheo commented on web/src/pages/index.tsx
> +  };
상수같은경우는 저는 왠만하면 빼는 편이긴한데
타입추론으로인해 먼저 코드에 문제가 생길일이 없다는건 너무 공감됩니다 ㅋㅋ
저 같은 경우는 해당 타입의 내용이 수정될 경우를 생각해서 상수로 뺐었던건데요..

예를 들어 지금은 `light` 라고 했다가 `lightTheme` 이라던가 명칭을 수정하게되면 모두 수정해야 되다보니
이런 고민을 하다가 상수로 뺐었습니다.

이렇게 절대 수정이 안될 상수는 필요가 없긴 한데 
습관적으로 빼긴 했었습니다..

2021-09-27 10:49 UTC, HanCheo commented on web/src/styles/BreadMapTheming.tsx
> +import { createContext, useContext, useState, useCallback } from 'react';
어우 너무 감사합니다 :)

2021-09-27 10:52 UTC, wooogi123 commented on web/src/pages/index.tsx
> +  };
전 평소에 작업할때 타입추론을 vscode가 뻗을정도로 쓰는걸 좋아하는 편이라서 상수대신 타입을 적용시켜두는 편인데,

> 예를 들어 지금은 light 라고 했다가 lightTheme 이라던가 명칭을 수정하게되면 모두 수정해야 되다보니
> 이런 고민을 하다가 상수로 뺐었습니다.
요런 케이스는 아예 해당 type 자체가 외부로 노출될 필요 없게, toggleTheme를 `BreadmapTheming.tsx` 안에 넣어서 `useThemeToggle` 선언만 외부로 노출시키는 방법도 있을것같아요!

2021-09-27 11:23 UTC, HanCheo commented on web/src/pages/index.tsx
> +  };
왕 너무좋아요 코드 확줄겟네요

2021-09-27 16:05 UTC, wooogi123 requested changes

2021-09-27 16:05 UTC, wooogi123 commented on web/src/styles/BreadMapTheming.tsx
> +  const [themeName, setThemeName] = useState<Theme>(THEME.light);
요기 state가 가지고 있는 값이 Theme라서 변수명을 theme로 변경하는게 좋을거같아요!

2021-09-27 16:05 UTC, wooogi123 commented on web/src/styles/BreadMapTheming.tsx
> +  }, [themeName]);
요기 비교 연산자 부분은 동일 객체니까 === 으로 동등 연산 비교하면 좋을거같아요

그리고 state가 전체 테마를 들고있을 필요는 없으니까 key만 들고 있어도 괜찮을꺼 같은데 어떻게 생각하세요?

2021-09-28 03:06 UTC, HanCheo commented on web/src/styles/BreadMapTheming.tsx
> +  }, [themeName]);
맞죠 궅이 다들고 있을 필요는 없겠네요 !!

2021-09-28 03:08 UTC, wooogi123 commented on web/src/styles/BreadMapTheming.tsx
> +  }, [themeName]);
> 맞죠 궅이 다들고 있을 필요는 없겠네요 !!

넵 그리고 state에 들어가는게 객체여서 setState랑 비교연산시에도 문제 생길 수 있을꺼같아용

2021-09-28 03:12 UTC, wooogi123 requested changes

2021-09-28 03:12 UTC, wooogi123 commented on web/src/styles/BreadMapTheming.tsx
> +    themeName === 'light' ? setThemeName('dark') : setThemeName('light');
제가 너무 많은 코멘트를 다는거 같기는 한데..

요 부분에서 `setThemeName((prev) => prev === 'light' ? 'dark' : 'light');` 요런식으로 처리하면 useCallback을 통한 메모이제이션 필요도 없을것같습니당

2021-09-28 03:22 UTC, HanCheo commented on web/src/styles/BreadMapTheming.tsx
> +    themeName === 'light' ? setThemeName('dark') : setThemeName('light');
오 개쩐다 useState의 set 부분에서 이전 값을 참조할수 있군요.
처음알았어요..

2021-09-28 03:28 UTC, wooogi123 approved these changes
lgtm 👍

2021-09-29 13:02 UTC, seokzin approved these changes
코드 리뷰 짱입니다..!

2021-09-29 13:02 UTC, merged