[#16] 기능 : map 화면에 추가
depromeet/bread-map-front pull request #24
Opened 2021-09-29 13:10 UTC by jellybrown

## 개요 및 변경 사항 
map service를 이용해서 화면에 map을 렌더링합니다.

## 관련 이슈 

closes #16 

## 추가 구현 필요사항
map 관련된 로직을 앞으로 작성해야 할 것 같습니다 :)

## 스크린샷 
<img src="https://user-images.githubusercontent.com/59910838/135273851-88c0f267-1eaf-412c-9179-411b0bf41060.png" width="400" />

2021-09-29 13:21 UTC, wooogi123 requested changes

2021-09-29 13:21 UTC, wooogi123 commented on web/package.json
> +    "@types/navermaps": "^3.0.9",
요거 타입 정의라서 devDependencies로 옮기면 좋을것같아요!

2021-09-29 13:21 UTC, wooogi123 commented on web/src/pages/map.tsx
> +      );
요 부분에서
```tsx
const naverMapNamespace = naverMapInstance.getServiceNamespace();
if (mapInstance.current !== null) return;
mapInstance.current = new naverMapNamespace.Map(
  el,
  { zoom: 10, },
);
```
요런식으로 namespace 따로 뽑아서 해도 좋을꺼 같아요!

2021-09-29 13:21 UTC, wooogi123 commented on web/src/utils/NaverMapService.tsx
> +export const NScript = ({ children }: { children: React.ReactNode }) => {
요거 컴포넌트 이름을 `NaverMapScript` 같은식으로 좀 더 직관적으로 바꾸면 좋을것같아요!

2021-09-29 14:40 UTC, HanCheo commented
끄악 제꺼 pr 머지된거 pull 받으셔야되영

2021-09-29 15:02 UTC, seokzin approved these changes
고생하셨습니다. 재욱님 상세한 피드백 굿입니다.

2021-09-29 15:58 UTC, wooogi123 commented on web/src/utils/NaverMapService.tsx
> +}
요 부분 저렇게 class export 하는 방법도 있는데,

```tsx
src/lib/NaverMapService.ts

class NaverMapService {
  private isInitialized: boolean = false;

  constructor() {}

  onScriptLoaded() {
    this.isInitialized = true;
  }

  get ns() {
    return window.naver.maps;
  }
}

export default new NaverMapService();

---

src/providers/NaverMapProvider.tsx
import * as React from 'react';
import NaverMapService from 'src/lib/NaverMapService';

type NaverMapInstance = typeof NaverMapService;
const NaverMapContext = React.createContext<NaverMapInstance | null>(null);

interface NaverMapProviderProps {
  children: React.ReactNode;
}
const NaverMapProvider = ({ children }: NaverMapProviderProps) => {
  const [instance] = React.useState<NaverMapInstance>(NaverMapService);

  return (
    <NaverMapContext.Provider value={instance}>
      <Script
        src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_ID}`}
        onLoad={() => {
          instance.onScriptLoaded();
        }}
      />
      {children}
    </NaverMapContext.Provider>
  );
};

export default NaverMapProvider;

export const useNaverMap = () => {
  const instance = React.useContext(NaverMapContext);
  if (instance === null) throw new Error('NaverMapContext is provide null');
  return instance.ns;
}

---

src/pages/map.tsx

/** 생략 */
const DisplayMap: React.FC = () => {
  const naverMap = useNaverMap();
  const ref = React.useRef<HTMLDivElement | null>(null);
  const mapInstance = React.useRef<naver.maps.Map | null>(null);

  React.useEffect(() => {
    const el = ref.current;
    if (el === null) return;

    setTimeout(() => {
      if (mapInstance.current !== null) return;
      mapInstance.current = new naverMap.Map(el, { zoom: 10 });
/** 생략 */
```

요런 느낌으로 파일 분할해서 작업하는건 어떨까요?

2021-09-30 00:39 UTC, HanCheo requested changes

2021-09-30 00:39 UTC, HanCheo commented on web/src/utils/NaverMapService.tsx
> +const NaverMapContext = React.createContext<NaverMapService | null>(null);
컨텍스트 안써도 될꺼같은데요..?

```javascript
//./utils/NaverMapService.tsx


export const NScript = ({ children }: { children: React.ReactNode }) => {
  const [isLoaded, setIsLoaded] = React.useState<boolean>(false);

  return (
    <>
      <Script
        src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_ID}`}
        onLoad={() => {
          setIsLoaded(true);
        }}
      />
      {isLoaded ? children : 'loading'}
    </>
  );
};

export const useNaverMapService = () => {
  const instance = window.naver.maps;
  if (instance === null) throw new Error();
  return instance;
};

//---

//pages.tsx

 const DisplayMap: React.FC = () => {
//...
  React.useEffect(() => {
    const el = ref.current;
    if (el === null || mapInstance.current !== null) return;

    mapInstance.current = new naverMapInstance.Map(el, {
      zoom: 10,
    });
  });

  return <MapDiv ref={ref}></MapDiv>;
};
```
이렇게 하심 setTimeout도 안써도 될거같아요 !

2021-09-30 00:45 UTC, HanCheo commented on web/src/utils/NaverMapService.tsx
> +}
`lib` !!! 저두 이전에는 이렇게 외부 스크립트 또는 외부 api를 사용할때는 lib폴더로 구분했어요 !!

2021-09-30 06:26 UTC, jellybrown commented on web/package.json
> +    "@types/navermaps": "^3.0.9",
알겠습니다!

2021-09-30 06:31 UTC, jellybrown commented on web/src/pages/map.tsx
> +      );
이렇게 분리할 수가 있는거군요..! 가독성 좋아진거 같습니다 👍

2021-09-30 06:37 UTC, jellybrown commented on web/src/utils/NaverMapService.tsx
> +export const NScript = ({ children }: { children: React.ReactNode }) => {
꼼꼼하십니다,,, 반영하겠습니다!

2021-09-30 06:53 UTC, jellybrown commented on web/src/utils/NaverMapService.tsx
> +const NaverMapContext = React.createContext<NaverMapService | null>(null);
오 한철님이 말씀해주신대로 해보니까 코드가 더 깔끔해지고 가독성 좋아진것 같습니다 !!
근데 그럼 `NaverMapService` 가  필요없어지는데 없애도 되나요..?

2021-09-30 06:55 UTC, jellybrown commented on web/src/utils/NaverMapService.tsx
> +}
아하 외부 서비스에 관련된건 `lib`에 하는거군요..! 감사합니다 반영하겠습니다 🙏

2021-09-30 07:00 UTC, jellybrown commented on web/src/utils/NaverMapService.tsx
> +}
아래 한철님이 context 없애는 걸로 피드백 주셨는데, 
```ts
return (
    <>
      <Script
        src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_ID}`}
        onLoad={() => {
          setIsLoaded(true);
        }}
      />
      {isLoaded ? children : 'loading'}
    </>
```
이렇게 하니까 좀 더 보기편한거 같습니다!
반영하고나서 provider 말고 `lib/NaverMapService.ts` 로 해도괜찮을까요?.?

2021-09-30 10:46 UTC, wooogi123 commented on web/src/utils/NaverMapService.tsx
> +}
@jellybrown  요러면 NaverMapService class와 Context api가 둘다 사라지니까 단순 컴포넌트로 위치시키면 되지 않을까요? 요 구조로 간다면 현재 코드 기준으로 `src/pages/map.tsx`에 바로 Script를 넣는 방향이 좋을 것 같아요

2021-10-01 00:35 UTC, HanCheo commented on web/src/utils/NaverMapService.tsx
> +const NaverMapContext = React.createContext<NaverMapService | null>(null);
넵 없애두 될거같아요 컴포넌트화 해서 컴포넌트에 넣으면 될듯합니당

2021-10-01 03:14 UTC, jellybrown commented on web/src/utils/NaverMapService.tsx
> +}
반영하도록 하겠습니다 ..! 친절한 설명 감사해요 😃

2021-10-01 05:11 UTC, wooogi123 approved these changes
lgtm 👍

2021-10-01 05:37 UTC, HanCheo approved these changes
초공 🤩

2021-10-01 12:52 UTC, merged