기능: 내 위치 버튼을 통한 현재 위치로 지도 이동
depromeet/bread-map-front pull request #37
Opened 2021-10-08 05:59 UTC by HanCheo

## 개요 및 변경 사항 

1. 맵 버튼 추가 
현 위치로 이동
현재 맵의 가운데에 마커 꽃기
2. naver.maps.Point 타입 확장 (x, y 가져올수 있도록)
3. 테스트 유틸 추가 (theme 적용)
4. babel (styled-component 설정) 추가, material icon 추가
5. yarn dev 브라우저 자동 오픈 추가

 

## 관련 이슈 

close #28
close #45 
close #35

## 추가 구현 필요사항

## 스크린샷

2021-10-08 08:38 UTC, wooogi123 requested changes

2021-10-08 08:38 UTC, wooogi123 commented on web/src/components/common/mapButton/MapButton.tsx
> +}
이 부분 `React.HTMLAttributes<HTMLButtonElement>` 로 대체 가능할 것 같아요

2021-10-08 08:38 UTC, wooogi123 commented on web/src/styles/styled.d.ts
> +      boxShadow: string,
요거 타입이니까 `,` -> `;` 로 바꾸면 좋을 것 같아요!

2021-10-08 08:38 UTC, wooogi123 commented on web/src/components/home/mapButtons/index.tsx
> +import MapButton from '../../common/mapButton/MapButton';
이거 `mapButtons`는 home 하위에 존재하는데, `MapButton` 은 따로 common에 넣으신 이유가 있나요?

2021-10-08 08:38 UTC, wooogi123 commented on web/.babelrc
> +  "plugins": ["@emotion/babel-plugin", "babel-plugin-styled-components"]
이거 현재 `styled-components`를 사용하지 않는데 따로 의존성 추가하신 이유 있나요?

2021-10-08 08:38 UTC, wooogi123 commented on web/src/types/naverMap.d.ts
> +}
이 부분 현재 구현을 `lib/navermap` 하위에 은닉해놓은 상태라서 없어도 될꺼같은데 어떻게 생각하시나요?

2021-10-08 09:10 UTC, HanCheo commented on web/.babelrc
> +  "plugins": ["@emotion/babel-plugin", "babel-plugin-styled-components"]
아래와 같은 형태로 컴포넌트를 오버라이드 해서 구현하면
구현은 되는데 실제 웹에서는 오류가 나더라구요
emotion/styled가 styled-components랑 동일한 기능을 해서 적용이 되는 것 같습니다.

[참고](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=qls0147&logNo=221614457064)
```
styled(ReactComponent)`
 ...css
`
```

2021-10-08 10:17 UTC, HanCheo commented on web/src/components/home/mapButtons/index.tsx
> +import MapButton from '../../common/mapButton/MapButton';
맵에서 쓰는 기본 버튼 컴포넌트로 정한건데 생각해보니 따로 뺄 필요가 없었네용 
궅궅

2021-10-09 04:38 UTC, jellybrown commented on web/src/components/common/mapButton/MapButton.spec.tsx
> +});
질문있습니다!
test.tsx는 기능에 대한 테스트고 spec.tsx는 컴포넌트 테스트인가요?

2021-10-09 05:43 UTC, seokzin approved these changes
궁금한 부분인데, PR에 올라온 파일 중 gitignore에 들어갈 파일들은 없나요?
뭔가 zip 확장자가 많아서 질문 드려용

2021-10-09 06:45 UTC, HanCheo commented on web/src/components/common/mapButton/MapButton.spec.tsx
> +});
아뇨 ! 이부분은 저도 뭘로 나누는지는 잘 모르겠네요.. 
저 파일을 spec으로 한 이유는
제 vsc오류인것 같은데 depth가 깊어지면 test로 했을 때 경로를 못찾더라구요;;
그래서 spec으로 바꿨는데 이것도 test로 통일해야겟어영

감사합니당 :)

추가적으로 spce과 test를 나누는건 저도 찾아봣는데 정확하게는 잘 모르겟더라구요
[참고](https://sites.google.com/site/unclebobconsultingllc/specs-vs-tests)

2021-10-10 11:27 UTC, wooogi123 commented on web/src/lib/navermap/NaverMapGoToMyPosition.tsx
> +const NaverMapGoToMyPosition = () => {
요거 훅이니까 `useNaverMapGoToMyPosition` 같은 네이밍으로 바꾸는게 좋을 것 같아요!

2021-10-10 11:30 UTC, wooogi123 commented on web/src/components/home/MapButtonsWrap.tsx
> +    })();
이 부분 `goToMyPosition` 이후에 실행시킬 코드가 없으니까 iife 로 묶을 필요 없이 goToMyPosition 만 호출시켜도 될꺼같아요!

2021-10-10 11:31 UTC, wooogi123 commented on web/src/components/home/MapButtonsWrap.tsx
> +        </MapButton>
`onClick` handler가 현재 존재하지 않으니까 제거해도 될 것 같습니다

2021-10-10 11:32 UTC, wooogi123 commented on web/src/components/home/MapButton.test.tsx
> +it('home/Card', () => {
요거 테스트 컴포넌트가 MapButton이니까 `home/MapButton` 같은 이름이 좋을꺼같아요

2021-10-10 11:32 UTC, wooogi123 commented on web/package.json
> +    "@types/material-ui": "^0.21.9",
요것도 사용하지 않으니 제거해도 좋을 것 같습니다

2021-10-13 08:24 UTC, HanCheo commented on web/src/lib/hooks/useMap.tsx
> +export default useMap;
넵넵

2021-10-14 00:20 UTC, wooogi123 commented on web/next.config.js
> +};
svgr 없이 svg 처리 하고 있어서 이 부분도 제거하면 될 것 같습니다

2021-10-14 00:20 UTC, wooogi123 commented on web/package.json
> +    "@types/material-ui": "^0.21.9",
요거 확인 다시 한번 해주세용 @HanCheo

2021-10-14 00:24 UTC, wooogi123 commented on web/src/components/daedong/CategoryCard.tsx
> +interface IProps {
요거 인터페이스 앞에 I prefix 다는거 권장되지 않는 스타일 패턴이라서, CategoryCardProps 같은 이름으로 바꾸는게 좋을 것 같아요

ref:
https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md#interface
https://google.github.io/styleguide/tsguide.html#naming-style

2021-10-14 00:26 UTC, wooogi123 commented on web/src/components/daedong/CategoryCard.tsx
> +  };
이 부분 prop 변경으로 인한 rendering이 원할하게 하기 위해

```ts
interface CategoryCardProps {
  name: string;
  checked: boolean;
}

const CategoryCard: React.FC<CategoryCardProps> = ({ name, checked }) => {
  ...
};
```

구조가 더 좋을 것 같은데 어떻게 생각하시나요?

2021-10-14 00:29 UTC, wooogi123 commented on web/src/types/index.d.ts
> +}
svg 파일 react component로 뽑아서 사용중이라 해당 타입 정의는 없어도 될 것 같습니다

2021-10-14 00:29 UTC, wooogi123 commented on web/tsconfig.json
> +      "@/*": ["./*"],
json에서 trailing comma 넣으면 안되요!

2021-10-14 01:45 UTC, HanCheo commented on web/src/components/daedong/CategoryCard.tsx
> +  };
오 좋아용 :)

2021-10-14 01:47 UTC, HanCheo commented on web/src/components/daedong/CategoryCard.tsx
> +interface IProps {
옹 감사 합니다 :)

2021-10-14 04:54 UTC, wooogi123 commented on web/public/assets/bread.svg
> +</svg>
@jellybrown 넵 용량 차이가 제일 크고, 불필요한 path들도 어느정도 정리해줘요!

2021-10-15 07:38 UTC, wooogi123 commented on web/src/components/daedong/CategoryCard.test.tsx
> +  const dom = render(<CategoryCard category={MOCK_CATEGORY} />);
컴포넌트 변경 사항이 테스트에 적용이 안되어있어서 확인 부탁드립니다!

2021-10-15 08:20 UTC, wooogi123 approved these changes
lgtm 👍

2021-10-16 11:05 UTC, merged