기능/#75
depromeet/bread-map-front pull request #89
Opened 2021-11-05 14:58 UTC by seokzin

## 개요 및 변경 사항 

## 관련 이슈 

closes 

## 추가 구현 필요사항

## 스크린샷

2021-11-06 05:54 UTC, wooogi123 requested changes
react-daum-postcode 해당 패키지 삭제된 것만 다시 설치하면 될것같습니다

2021-11-06 10:20 UTC, HanCheo requested changes
- 라우팅이 /search 인지 daedong/search 인지? 현재 Footer 파일의 라우팅을 따르는 것인가요?
 `/search` 가 맞아요!

- 디자인 시스템 처음이라 어떻게 사용하는지 참고할 PR 있을까요?
  마땅히 디자인시스템이라고 할만한게 없는데.....ㅠㅠ PR참고는.. 잘 모르겟네요...다른분들 도움!!

- 중앙 정렬할 때 Footer 높이가 포함되지 않는 이슈가 있음
`min-height:100vh` 때문에 나타나는 거네요. 스크롤이 있는것을 보아하니 footer가 아니라 header의 높이만큼 높아진것 같아요. footer은 fixed라 영향을 주진않은것 같은데... 어차피 페이지를 감싸는 컴포넌트의 `height`는 무조건 100vh로 되어야 하기때문에 특별한 상황이 아닌이상 내부에서 새롭게 100vh로 높이를 설정해주는건 좋아보이진 않아요. `min-height`는 하위 엘리먼트에서 height값으로 상속을 받을 수 없기 때문에 더욱이 그렇죠. 
```typescript

const Base = styled.div`
  height: calc(100vh - ${({theme}) => theme.height.footer}px);
  display:flex;
  flex-direction: column;
`;
const Layout = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
`;
```
요렇게 하면 스크롤도 안생기구 중앙정렬이 될것 같은데요..?? 물론 footer값의 height는 빼줘야 될것 같긴합니다...


- 그 전에 Footer는 탐색 페이지에서 빼도 상관 없나요?
   저도 탐색페이지에서는 빼도 될것 같기는 해요 :) `_app.tsx`에 푸터를 넣어놓고 푸터를 안쓰는 곳에서만 `z-index`로 푸터 위를 덮어서 안보이게 하는 편이 좀더 나을수도 있겠네요.

- Icons에 중복이 몇 보였습니다. - Setting, SettingIcon
동일한 아이콘이면 사용처 확인및 수정해서 하나만남기구 지워주셔도 됩니당!! 이런 것들은 pr올릴때 같이 잘 봣어야 했는데 실수네요 ㅠ

- div 분리가 조금 많은 것 같습니다.. 팁 있을까요?
div 분리라... styled 컴포넌트형태에서는 컴포넌트 명을 사용하기 때문에 템플릿을 작성하는 공간에서는 div태그를 남발해도 스타일컴포넌트 명으로 대체되기 때에 크게 신경쓰지 않는 편입니다. 단순히 div만 사용해서 걱정된다 싶다면 스타일 컴포넌트 명칭을 잘 해주면 문제는 없을것 같아요.
그게 아니라 로봇의 효율성 웹 검색등을 위해서 문제가 있을 것 같다고 생각을 기반에 두시고 얘기하신거라면 [시멘틱태그](https://www.w3schools.com/html/html5_semantic_elements.asp)를 기반으로 분리하시는 방향도 좋지요. [HTML5 Outline](https://naradesign.github.io/html5-outline.html)을 이해하시면 크게 도움될것 같아용 :) 저두 면접보면서 주워들은 키워드..

2021-11-06 10:31 UTC, wooogi123 commented
@seokzin @HanCheo @jellybrown

중복 Icon관련해서는 기존에 디자인 에셋을 가져오기 전 icon, 가져온 후 icon이 공존하는 상태여서 제가 따로 작업해둔 컴포넌트의 경우 `${ICON_NAME}Icon.tsx` 로 구분지어놓은 상태입니다.

의도적으로 중복되게 정리해둔 상태라서 당장은 무시하셔도 될 것 같아요

2021-11-07 01:22 UTC, seokzin commented
@HanCheo
상세한 리뷰 감사해요..! 짱짱ㅎㅎ

2021-11-07 17:35 UTC, wooogi123 approved these changes

2021-11-08 02:21 UTC, HanCheo approved these changes

2021-11-08 02:27 UTC, merged