[#74] 프로필 페이지 기본 틀 구현
depromeet/bread-map-front pull request #91
Opened 2021-11-06 10:27 UTC by jellybrown

## 개요 및 변경 사항 
- 프로필, 프로필 수정, 설정 구현
## 관련 이슈 

closes #74 

## 추가 구현 필요사항
- 프로필 페이지 탭별 구현 필요

<img src="https://user-images.githubusercontent.com/59910838/140606398-443f5ad4-578c-413d-96b9-8150df48b3ce.png" width="300"/>

2021-11-06 10:38 UTC, wooogi123 requested changes

2021-11-06 10:38 UTC, wooogi123 commented on web/src/components/UserProfile/MainProfile.tsx
> +}
요거 enum의 경우에는 빌드타임에서 실제 객체가 생성되서

```ts
type TabType = 'wish' | 'went' | 'review';

const [tab, setTab] = React.useState<TabType>('wish');
```
요런식으로 쓰는게 더 깔금할 것 같아용

reference
https://fe-developers.kakaoent.com/2021/211012-typescript-tip/

2021-11-06 12:09 UTC, HanCheo approved these changes

2021-11-07 01:18 UTC, seokzin approved these changes

2021-11-09 06:10 UTC, merged